# Generated by Django 2.2.6 on 2019-12-21 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('city', models.CharField(max_length=140)),
                ('state', models.CharField(max_length=140)),
                ('country', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('latin', models.CharField(max_length=140)),
                ('edible', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Place'),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Variety'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('mushroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Mushroom')),
            ],
        ),
        migrations.AddField(
            model_name='mushroom',
            name='shares',
            field=models.ManyToManyField(to='main_app.Share'),
        ),
    ]
