# Generated by Django 2.2.6 on 2019-12-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191221_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroom',
            name='images',
        ),
    ]
