# Generated by Django 2.2.6 on 2019-12-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_mushroom_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroom',
            name='note',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='shares',
            field=models.ManyToManyField(blank=True, to='main_app.Share'),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='place',
            name='state',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='share',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='variety',
            name='latin',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
