# Generated by Django 2.2.6 on 2019-12-23 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20191221_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mushroom',
            options={'ordering': ['-date']},
        ),
    ]
