# Generated by Django 2.2.6 on 2019-12-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_mushroom_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='place_name',
        ),
        migrations.RenameField(
            model_name='share',
            old_name='name',
            new_name='share_name',
        ),
        migrations.RenameField(
            model_name='variety',
            old_name='name',
            new_name='variety_name',
        ),
    ]
